# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentID', models.IntegerField(blank=True, null=True)),
                ('AgentIP', models.GenericIPAddressField(protocol='ipv4')),
                ('SetupPlatform', models.CharField(blank=True, max_length=100, null=True)),
                ('AgentState', models.CharField(blank=True, max_length=100, null=True)),
                ('DownloadPercentage', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'ipmonitor_agentdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serialnumber', models.IntegerField(blank=True, null=True)),
                ('Platform', models.CharField(blank=True, max_length=100, null=True)),
                ('BuildID', models.IntegerField(blank=True, null=True)),
                ('BuildName', models.CharField(blank=True, max_length=100, null=True)),
                ('StatusType', models.CharField(blank=True, max_length=100, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ipmonitor_sanitymaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MachineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.IntegerField(choices=[(1, 'Windows PC'), (2, 'Ubuntu')], default=1)),
                ('operating_system', models.IntegerField(choices=[(1, 'Windows 10 Aniversary'), (2, 'Windows 10 Pro'), (3, 'Windows 10'), (4, 'Windows 8'), (5, 'Windows 7'), (6, 'Ubuntu')], default=1)),
                ('v4_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('hostName', models.CharField(max_length=100, unique=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('symantic', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('cabinet_esxi', models.CharField(blank=True, max_length=100, null=True)),
                ('esxi_server_id', models.CharField(blank=True, max_length=100, null=True)),
                ('softwares', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.IntegerField(choices=[(1, 'ESXI'), (2, 'AWV Server')], default=1)),
                ('operating_system', models.IntegerField(choices=[(1, 'ESXI'), (2, 'MSL')], default=1)),
                ('v4_ip', models.GenericIPAddressField(protocol='ipv4')),
                ('fqdn', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_creator', to=settings.AUTH_USER_MODEL)),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to=settings.AUTH_USER_MODEL)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_updator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
