# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmonitor', '0002_serverdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetail',
            name='fqdn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]