# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmonitor', '0003_auto_20180307_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgentID', models.IntegerField(blank=True, null=True)),
                ('AgentIP', models.GenericIPAddressField(protocol='ipv4')),
                ('SetupPlatform', models.CharField(blank=True, max_length=100, null=True)),
                ('AgentState', models.CharField(blank=True, max_length=100, null=True)),
                ('DownloadPercentage', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'ipmonitor_agentdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serialnumber', models.IntegerField(blank=True, null=True)),
                ('Platform', models.CharField(blank=True, max_length=100, null=True)),
                ('BuildID', models.IntegerField(blank=True, null=True)),
                ('BuildName', models.CharField(blank=True, max_length=100, null=True)),
                ('StatusType', models.CharField(blank=True, max_length=100, null=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ipmonitor_sanitymaster',
                'managed': False,
            },
        ),
    ]